/**
 * 自动机器人AI
 * 专门用于GitHub Action和CL自动机器人
 * 每回合自动执行git原子操作
 */
class AutoBotAI {
    constructor(gameState, cardFactory, player, botType, gitOperations = null) {
        this.gameState = gameState;
        this.cardFactory = cardFactory;
        this.player = player;
        this.botType = botType; // 'github-action' 或 'cl-bot'
        // 使用传入的操作列表，如果没有则使用默认列表
        this.gitOperations = gitOperations || [
            'add', 'commit', 'push', 'pull', 'fetch',
            'branch', 'checkout', 'merge', 'status', 'log'
        ];
    }
    
    /**
     * 从允许的操作列表中获取随机卡牌
     */
    getRandomCardFromOperations() {
        if (!this.gitOperations || this.gitOperations.length === 0) {
            return this.cardFactory.getRandomCard();
        }
        
        // 从CARD_DATA中找到匹配的操作（CARD_DATA是全局变量）
        if (typeof CARD_DATA === 'undefined') {
            return this.cardFactory.getRandomCard();
        }
        
        const availableCards = CARD_DATA.filter(card => 
            this.gitOperations.includes(card.id)
        );
        
        if (availableCards.length === 0) {
            return this.cardFactory.getRandomCard();
        }
        
        // 随机选择一个操作
        const randomIndex = Math.floor(Math.random() * availableCards.length);
        const cardData = availableCards[randomIndex];
        
        return this.cardFactory.createCard(cardData);
    }

    /**
     * 执行自动回合（每回合开始时调用）
     * 简化逻辑：直接抽取一张牌并打出
     * @param {Function} logCallback - 日志回调函数
     */
    executeTurn(logCallback = null) {
        if (this.player.health <= 0) {
            return;
        }

        // 直接从允许的操作列表中抽取一张牌
        const card = this.getRandomCardFromOperations();
        if (!card) {
            if (logCallback) {
                const botName = this.botType === 'github-action' ? 'GitHub Action' : 'CL自动机器人';
                logCallback(`🤖 ${botName} 无法获取卡牌，跳过回合`, this.player.name);
            }
            return;
        }

        // 检查卡牌是否有效果组件
        if (!card.effectComponent) {
            if (logCallback) {
                const botName = this.botType === 'github-action' ? 'GitHub Action' : 'CL自动机器人';
                logCallback(`🤖 ${botName} 的卡牌 ${card.name} 没有效果，跳过`, this.player.name);
            }
            return;
        }

        // 确定目标
        const target = card.type === 'heal' 
            ? this.player.name 
            : this.selectTarget();

        // 消耗能量（虽然能量是999，但为了保持一致性）
        this.player.consumeMana(card.cost);

        // 执行卡牌效果
        const cardEffect = new CardEffect(this.gameState, null, this.cardFactory);
        const result = cardEffect.execute(card, target, this.player.name);

        // 记录卡牌打出历史
        if (this.gameState.recordCardPlay) {
            this.gameState.recordCardPlay(card, this.player.name, this.gameState.turnNumber);
        }

        // 显示打出的卡牌
        if (this.gameState.cardAnimation && this.gameState.cardRenderer) {
            this.gameState.cardAnimation.showPlayedCardDirectly(
                card,
                this.player.name,
                this.gameState.cardRenderer,
                this.gameState.currentTurnCards
            );
        }

        // 触发事件
        if (this.gameState.eventSystem) {
            this.gameState.eventSystem.emit('card:played', {
                card: {
                    id: card.id,
                    baseId: card.baseId,
                    name: card.name,
                    icon: card.icon,
                    cost: card.cost,
                    power: card.power || 0,
                    heal: card.heal || 0,
                    draw: card.draw || 0,
                    type: card.type,
                    isAutoGenerated: true,
                    isFromBuff: true,
                    isFromAutoBot: true
                },
                player: this.player.name,
                target: target
            });
            this.gameState.eventSystem.emit('gitgraph:update');
        }

        // 记录日志
        if (logCallback) {
            const botName = this.botType === 'github-action' ? 'GitHub Action' : 'CL自动机器人';
            logCallback(`🤖 ${botName} 自动执行了 ${card.icon} ${card.name}！`, this.player.name);
        }
    }

    /**
     * 选择目标（选择敌对玩家）
     */
    selectTarget() {
        const enemies = this.gameState.getEnemyPlayers();
        if (enemies.length === 0) {
            return this.player.name; // 没有敌人，对自己使用
        }
        // 随机选择一个敌人
        return enemies[Math.floor(Math.random() * enemies.length)].name;
    }
}

