/**
 * 卡牌效果处理器
 * 负责执行卡牌效果并处理相关逻辑
 * 使用效果组件系统
 */
class CardEffect {
    constructor(gameState, logSystem, cardFactory = null) {
        this.gameState = gameState;
        this.logSystem = logSystem;
        this.cardFactory = cardFactory;
    }

    /**
     * 格式化卡牌详细信息
     * @param {Card} card - 卡牌实例
     * @returns {string} 格式化后的卡牌信息字符串
     */
    formatCardDetails(card) {
        const parts = [];
        
        // 卡牌名称和图标
        parts.push(`${card.icon} ${card.name}`);
        
        // 费用
        parts.push(`💎${card.cost}`);
        
        // 数值效果（如果有）
        const effects = [];
        if (card.power > 0) {
            effects.push(`⚔️${card.power}`);
        }
        if (card.heal > 0) {
            effects.push(`💚${card.heal}`);
        }
        if (card.draw > 0) {
            effects.push(`📚${card.draw}`);
        }
        if (effects.length > 0) {
            parts.push(effects.join(' '));
        }
        
        // 类型（如果有特殊类型）
        if (card.type && card.type !== 'attack') {
            const typeMap = {
                'heal': '💚治疗',
                'special': '✨特殊',
                'buff': '🛡️增益'
            };
            parts.push(typeMap[card.type] || card.type);
        }
        
        return parts.join(' | ');
    }

    /**
     * 执行卡牌效果
     */
    execute(card, target, cardUser) {
        if (!card.effectComponent) {
            console.warn(`卡牌 ${card.name} 没有效果组件`);
            return null;
        }

        const context = {
            gameState: this.gameState,
            target: target,
            cardUser: cardUser,
            card: card,
            cardFactory: this.cardFactory
        };

        // 检查是否可以执行
        if (!card.effectComponent.canExecute(context)) {
            return null;
        }

        try {
            // 记录卡牌详细信息（只记录到开发者日志，不显示在弹幕）
            if (this.logSystem) {
                const cardDetails = this.formatCardDetails(card);
                this.logSystem.addLog({
                    userMessage: '', // 不显示在弹幕
                    devMessage: `[CardPlay] ${cardUser} 打出卡牌: ${cardDetails} | Target: ${target} | Mana: ${this.gameState.getCurrentPlayer().mana}/${this.gameState.getCurrentPlayer().maxMana}`
                }, cardUser);
            }

            // 执行效果
            const result = card.effectComponent.execute(context);
            
            // 触发卡牌使用事件（只发送必要的数据，避免循环引用）
            if (this.gameState.eventSystem) {
                this.gameState.eventSystem.emit('card:played', {
                    card: {
                        id: card.id,
                        name: card.name,
                        icon: card.icon,
                        cost: card.cost,
                        power: card.power || 0,
                        heal: card.heal || 0,
                        draw: card.draw || 0,
                        type: card.type,
                        isAutoGenerated: card.isAutoGenerated || false,
                        isFromBuff: card.isFromBuff || false,
                        isFromAutoBot: card.isFromAutoBot || false
                    },
                    player: cardUser,
                    target: target
                });
            }

            // 记录效果日志
            if (result && result.message && this.logSystem) {
                const source = result.source || cardUser;
                // 如果result中有userMessage和devMessage，使用它们；否则使用message
                if (result.userMessage !== undefined || result.devMessage !== undefined) {
                    this.logSystem.addLog({
                        userMessage: result.userMessage || '',
                        devMessage: result.devMessage || result.message
                    }, source);
                } else {
                    // 向后兼容：只提供了message
                    this.logSystem.addLog({
                        userMessage: '', // 不显示在弹幕
                        devMessage: `[CardEffect] ${result.message} | Source: ${source} | Card: ${card.name}`
                    }, source);
                }
            }

            return result;
        } catch (error) {
            console.error(`执行卡牌 ${card.name} 的效果时发生错误:`, error);
            if (this.logSystem) {
                this.logSystem.addLog({
                    userMessage: `卡牌 ${card.name} 效果执行失败！`,
                    devMessage: `[Error] 卡牌效果执行失败 | Card: ${card.name} | User: ${cardUser} | Target: ${target} | Error: ${error.message || error.toString()}`
                }, 'system');
            }
            return null;
        }
    }

    /**
     * 确定卡牌目标
     * @param {Card} card - 卡牌
     * @param {string} cardUser - 出牌者 ('player' 或 'opponent')
     */
    determineTarget(card, cardUser) {
        // 治疗牌总是对自己使用
        if (card.type === 'heal') {
            return cardUser;
        }
        
        // 攻击牌：从敌对玩家中选择（排除自动机器人）
        const enemyPlayers = this.gameState.getEnemyPlayers();
        if (enemyPlayers.length > 0) {
            // 优先选择玩家或对手（非自动机器人）
            const mainEnemy = enemyPlayers.find(p => p.name === 'player' || p.name === 'opponent');
            if (mainEnemy) {
                return mainEnemy.name;
            }
            // 如果没有主要对手，返回第一个敌对玩家（虽然理论上不应该有这种情况）
            return enemyPlayers[0].name;
        }
        
        // 如果没有敌对玩家，返回默认对手（向后兼容）
        return cardUser === 'player' ? 'opponent' : 'player';
    }
}

